FROM php:8.2-apache

RUN sed -ri -e 's!/var/www/html!/var/www/html/public!g' /etc/apache2/sites-available/*.conf \
 && sed -ri -e 's!/var/www/!/var/www/html/public!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

RUN /usr/sbin/a2enmod rewrite \
 && /usr/sbin/a2enmod headers \
 && /usr/sbin/a2enmod expires

RUN pecl install xdebug \
 && docker-php-ext-enable xdebug
